### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by huangzhengyang499** [FunCodersTeam/IPGW#1]
Thank you very much for your work!I hope you can continue this work.
It is worth mentioning that when I used this script today, I kept being prompted to login failure. May I ask why this situation is caused?
![image](https://github.com/FunCodersTeam/IPGW/assets/52780614/54ff7fad-0ae7-4379-a4ee-288c2badd979)

**Comment by guidons-master** [comment]
Thank you for your feedback!

Regarding the login failure issue you're experiencing, it's difficult for me to provide a specific answer without more information about the script you're using and the environment you're using it in. Generally, failed logins can occur for a variety of reasons, such as incorrect login credentials, account balance insufficient, network connection problems, server maintenance, or security measures such as two-factor authentication.

I recommend using the latest version of the script, which should provide more detailed error output and help you troubleshoot the issue.

I hope this information is helpful🤝

**Comment by huangzhengyang499** [comment]
Thank you for your prompt response and helpful information regarding the login failure issue. I appreciate your insight into the possible causes of this issue. 
After repeated checks, I found that the reason for the login failure was my account overdue, which has been solved now. 
🤝
